# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

version: "3.4"

services:
  app:
    image: maven:3-eclipse-temurin-17-alpine
    volumes:
      - ./:/code
      - ~/.m2/:/var/maven/.m2
    working_dir: /code
    env_file:
      - .env
    command: >
      mvn
        -Duser.home=/var/maven
        -Dspring-boot.run.profiles=local
        -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
        clean spring-boot:run

    tty: true
    environment:
      SERVER_PORT: ${SERVER_PORT}
      NINJA_BASE_URL: ${NINJA_BASE_URL}
      NINJA_HOST_URL: ${NINJA_HOST_URL}
      NINJA_QUERY_TIMEOUT_SEC: ${NINJA_QUERY_TIMEOUT_SEC}
      NINJA_RESPONSE_MAX_SIZE_MB: ${NINJA_RESPONSE_MAX_SIZE_MB}
      SECURITY_ALLOWED_ORIGINS: ${SECURITY_ALLOWED_ORIGINS}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_SSL_REQUIRED: ${KEYCLOAK_SSL_REQUIRED}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      LOG_APPLICATION_NAME: ${LOG_APPLICATION_NAME}
      LOG_APPLICATION_VERSION: ${LOG_APPLICATION_VERSION}
      JDBC_URL: ${JDBC_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAVEN_CONFIG: /var/maven/.m2
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "8000:8000"
    networks:
      - internal

networks:
  internal:
    external: false
