version: "3.4"

services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    restart: unless-stopped
    environment:
      _JAVA_OPTIONS: ${JAVA_OPTIONS}
    env_file:
      - .env
    healthcheck:
      test: (curl --fail http://localhost:${SERVER_PORT}/actuator/health || exit 1) && (curl --fail http://localhost:${SERVER_PORT} || exit 1)
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
